### ISSUE TITLE
Flux 4.0.0 Beta 2 load issue

### ISSUE THREAD

**Issue by RayzoRayy** [Szewek/Minecraft-Flux#30]
When loading Flux Beta 2 for 1.15.1, it says your MC mods.toml is missing. I do not believe Beta 1 had this issue. 
Forge 30.0.18
MC-1.15.1

**Comment by szeweq** [comment]
There is a small naming mistake made by IDE. I was refactoring "Minecraft-Flux" names to "Flux" (because CurseForge won't allow me to publish mod with "Minecraft" in title). Forge tries to find "flux" mod while "mcflux" was described in mods.toml file.

Fix is coming in the next update. I'm closing this issue manually since i won't publish source code to this repository until Preview Version is complete.
