### ISSUE TITLE
[1.10.2] Crash from placing forestry clockwork engine

### ISSUE THREAD

**Issue by Gayanfalor** [Szewek/Minecraft-Flux#4]
Hello, 

i got a crash when trying to place a clockwork engine from forestry, i asked on irc and they said me it seems coming from  minecraft-flux, that why this post ^^.

Here is the crashlog    [http://pastebin.com/Q4h5aQPn](url)

EDIT: Apparently this other crahslog is coming from minecraft-flux too   https://github.com/SonarSonic/Calculator/issues/186

**Comment by szeweq** [comment]
Minecraft-Flux doesn't do anything wrong when a new capability is being added. It only depends on other mods' `hasCapability` method. There is no _capability implementation standards_. That's why these crashes are very common and **mod authors MUST BE AWARE of it**.

Minecraft-Flux 1.4.0-b4 has new error reporting, so it may not crash but mods won't be fully supported. If you see an MCFlux error report (in logs) then copy it and send to related mod authors.
